# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "lsof -t -i:8081 | xargs -r kill -9 || true && go build -o ./tmp/main ./cmd/fenix" 
  bin = "./tmp/main"
  delay = 1000
  include_ext = ["go", "md"]
  exclude_dir = ["tmp", "output"]
  poll=true 

[run]
cmd = "./tmp/main"

[log]
  time = true
  level = "debug"

[misc]
  clean_on_exit = true

[watcher]
  poll = true
  poll_interval = 500
  recursive = true