@url = http://localhost:8080/r4

GET {{url}}/JAPAL
### 
GET {{url}}/Patient?_count=2&_offset=0
### 

### 
GET {{url}}/Observation?_count=2&_offset=0&code:in:https://www.hl7.org/fhir/observation-vitalsigns.html

###
GET {{url}}/Observation?_count=2&_offset=4?klasdf=123

###
GET {{url}}/Observation?_count=2&_offset=0


### JALA
GET {{url}}/Observation?_count=2

GET {{url}}/Observation?asdf=1912&code:in=1234,5678&jaaaaa=122121


### 
GET {{url}}/None?asdf=1912&code:in=1234,5678&jaaaaa=122121